In [1]:
import pandas as pd

In [3]:
data = pd.read_pickle('trust_data.p')

In [29]:
def re_map(face_id,rating):
    '''
    takes two series objects and creates a dictionary
    with face id as the key and trustworthy rating as the answer
    '''
    scoring = {}
    #for k,v in zip(face_id[6:],rating[6:]):
    for k,v in zip(face_id[6:-1],rating[6:-1]):
        scoring[k] = v
    return scoring

In [49]:
def change_by_map(face_id,scoring):
    '''
    takes faceid and rating and changes rating using scoring dict
    
    '''
    final=[]
    for face in face_id.tolist()[:-1]:
        final.append(scoring[face])
    final.append(0)
    return(final)

In [61]:
big_list = []
subjects = data.subject[::13]

for sub in subjects:
    subset_of_data = data[data.subject == sub]
    face_id = subset_of_data.faceID
    rating = subset_of_data.trustworthyRate
    scoring = re_map(face_id,rating)
    big_list += change_by_map(face_id,scoring)
print(big_list)

[8, 7, 6, 6, 8, 6, 8, 8, 6, 6, 6, 7, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 8, 4, 7, 5, 5, 4, 5, 7, 4, 5, 8, 4, 0, 7, 6, 7, 8, 7, 7, 7, 7, 8, 7, 6, 7, 0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 8, 9, 7, 8, 8, 8, 8, 7, 8, 9, 8, 8, 0, 6, 7, 6, 6, 7, 6, 6, 7, 6, 6, 6, 7, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 5, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 0, 7, 6, 5, 6, 5, 6, 6, 6, 7, 5, 5, 6, 0, 7, 5, 7, 5, 7, 7, 7, 7, 5, 7, 7, 5, 0, 8, 5, 7, 4, 4, 5, 8, 7, 5, 5, 4, 4, 0, 6, 5, 8, 7, 6, 8, 8, 8, 6, 6, 5, 7, 0, 6, 7, 8, 7, 7, 7, 7, 8, 6, 7, 7, 7, 0, 6, 7, 3, 6, 6, 5, 6, 5, 6, 3, 6, 7, 0, 8, 9, 7, 7, 4, 6, 6, 7, 7, 8, 9, 4, 0, 9, 8, 7, 8, 9, 9, 9, 7, 8, 9, 9, 8, 0, 7, 6, 6, 8, 9, 9, 9, 8, 6, 9, 7, 6, 0, 3, 5, 4, 6, 6, 5, 6, 4, 5, 3, 5, 6, 0, 7, 4, 6, 7, 6, 3, 3, 4, 7, 6, 6, 7, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 3, 7, 6, 3, 4, 6, 4, 6, 7, 6, 3, 3, 0, 7, 7, 7, 5, 5, 7, 7, 5, 7, 7, 5, 7, 0, 6, 6, 8, 7, 5, 7, 7, 6, 5, 6, 7, 8, 0]

In [65]:
data.trustworthyRate = big_list

In [66]:
data

,subject,id,expCode,age,gender,ethnicity,country,education,economics,quizAttempts,...,faceID,choice,choiceCongruent,trustworthyRate,reasonForExp,reasonCorrect,elapsedTime,responseTime,trialEndTime,date
0,03c2782a,1,llP1,26,1,7,United Stat,4,0,2,...,1,1,2,8,0,0,132.537,0.000,11:59:37,20/04/2016
1,03c2782a,2,llP1,26,1,7,United Stat,4,0,2,...,2,1,2,7,0,0,144.399,0.000,11:59:49,20/04/2016
2,03c2782a,3,llP1,26,1,7,United Stat,4,0,2,...,5,0,1,6,0,0,153.535,0.000,11:59:58,20/04/2016
3,03c2782a,4,llP1,26,1,7,United Stat,4,0,2,...,4,1,1,6,0,0,164.807,0.000,12:00:09,20/04/2016
4,03c2782a,5,llP1,26,1,7,United Stat,4,0,2,...,0,0,0,8,0,0,172.826,0.000,12:00:17,20/04/2016
5,03c2782a,6,llP1,26,1,7,United Stat,4,0,2,...,3,1,0,6,0,0,180.835,0.000,12:00:25,20/04/2016
6,03c2782a,7,llP1,26,1,7,United Stat,4,0,2,...,1,0,0,8,0,0,197.738,11.691,12:00:42,20/04/2016
7,03c2782a,8,llP1,26,1,7,United Stat,4,0,2,...,0,0,0,8,0,0,210.899,12.625,12:00:55,20/04/2016
8,03c2782a,9,llP1,26,1,7,United Stat,4,0,2,...,3,0,0,6,0,0,219.407,7.925,12:01:04,20/04/2016
9,03c2782a,10,llP1,26,1,7,United Stat,4,0,2,...,4,0,0,6,0,0,226.015,6.114,12:01:10,20/04/2016
10,03c2782a,11,llP1,26,1,7,United Stat,4,0,2,...,5,0,0,6,0,0,231.854,5.336,12:01:16,20/04/2016
11,03c2782a,12,llP1,26,1,7,United Stat,4,0,2,...,2,0,0,7,0,0,238.742,4.276,12:01:23,20/04/2016
12,03c2782a,13,llP1,26,1,7,United Stat,4,0,0,...,0,0,0,0,2,0,260.317,21.024,12:01:45,20/04/2016
13,1d72221b,1,llP1,44,1,2,United Stat,4,1,1,...,2,1,1,5,0,0,186.610,0.000,12:07:23,20/04/2016
14,1d72221b,2,llP1,44,1,2,United Stat,4,1,1,...,3,0,2,5,0,0,194.804,0.000,12:07:31,20/04/2016
15,1d72221b,3,llP1,44,1,2,United Stat,4,1,1,...,5,1,2,5,0,0,203.449,0.000,12:07:39,20/04/2016
16,1d72221b,4,llP1,44,1,2,United Stat,4,1,1,...,4,0,1,5,0,0,211.292,0.000,12:07:47,20/04/2016
17,1d72221b,5,llP1,44,1,2,United Stat,4,1,1,...,1,0,0,5,0,0,222.884,0.000,12:07:59,20/04/2016
18,1d72221b,6,llP1,44,1,2,United Stat,4,1,1,...,0,0,1,5,0,0,233.716,0.000,12:08:10,20/04/2016
19,1d72221b,7,llP1,44,1,2,United Stat,4,1,1,...,0,0,0,5,0,0,249.513,10.928,12:08:26,20/04/2016
20,1d72221b,8,llP1,44,1,2,United Stat,4,1,1,...,5,0,0,5,0,0,253.939,3.967,12:08:30,20/04/2016
21,1d72221b,9,llP1,44,1,2,United Stat,4,1,1,...,3,0,0,5,0,0,260.137,5.724,12:08:36,20/04/2016
22,1d72221b,10,llP1,44,1,2,United Stat,4,1,1,...,2,0,0,5,0,0,264.913,4.287,12:08:41,20/04/2016
23,1d72221b,11,llP1,44,1,2,United Stat,4,1,1,...,4,0,0,5,0,0,269.903,4.475,12:08:46,20/04/2016
24,1d72221b,12,llP1,44,1,2,United Stat,4,1,1,...,1,0,0,5,0,0,273.855,3.495,12:08:50,20/04/2016
25,1d72221b,13,llP1,44,1,2,United Stat,4,1,0,...,0,0,0,0,1,0,290.801,16.461,12:09:07,20/04/2016
26,3d643351,1,llP1,21,0,2,United Stat,4,0,5,...,2,1,2,8,0,0,1312.060,0.000,15:43:55,20/04/2016
27,3d643351,2,llP1,21,0,2,United Stat,4,0,5,...,0,0,1,4,0,0,1321.460,0.000,15:44:04,20/04/2016
28,3d643351,3,llP1,21,0,2,United Stat,4,0,5,...,5,1,1,7,0,0,1330.440,0.000,15:44:13,20/04/2016
29,3d643351,4,llP1,21,0,2,United Stat,4,0,5,...,3,1,1,5,0,0,1338.950,0.000,15:44:22,20/04/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,f2eb44cd,10,llP1,31,1,2,United Stat,5,0,1,...,3,0,0,6,0,0,235.435,5.366,18:39:57,20/04/2016
283,f2eb44cd,11,llP1,31,1,2,United Stat,5,0,1,...,0,0,0,3,0,0,239.329,3.421,18:40:01,20/04/2016
284,f2eb44cd,12,llP1,31,1,2,United Stat,5,0,1,...,2,0,0,3,0,0,243.076,3.281,18:40:05,20/04/2016
285,f2eb44cd,13,llP1,31,1,2,United Stat,5,0,0,...,0,0,0,0,2,0,260.105,16.569,18:40:22,20/04/2016
286,f271711d,1,llP1,36,0,2,United Stat,4,1,1,...,2,0,2,7,0,0,159.176,0.000,23:45:55,20/04/2016
287,f271711d,2,llP1,36,0,2,United Stat,4,1,1,...,4,1,1,7,0,0,168.270,0.000,23:46:04,20/04/2016
288,f271711d,3,llP1,36,0,2,United Stat,4,1,1,...,1,0,2,7,0,0,176.415,0.000,23:46:12,20/04/2016
289,f271711d,4,llP1,36,0,2,United Stat,4,1,1,...,5,1,1,5,0,0,193.572,0.000,23:46:30,20/04/2016
290,f271711d,5,llP1,36,0,2,United Stat,4,1,1,...,3,0,1,5,0,0,203.695,0.000,23:46:40,20/04/2016
291,f271711d,6,llP1,36,0,2,United Stat,4,1,1,...,0,0,1,7,0,0,216.080,0.000,23:46:52,20/04/2016
292,f271711d,7,llP1,36,0,2,United Stat,4,1,1,...,4,0,0,7,0,0,231.538,11.016,23:47:08,20/04/2016
293,f271711d,8,llP1,36,0,2,United Stat,4,1,1,...,5,0,0,5,0,0,238.268,5.880,23:47:14,20/04/2016
294,f271711d,9,llP1,36,0,2,United Stat,4,1,1,...,1,0,0,7,0,0,242.358,3.615,23:47:18,20/04/2016
295,f271711d,10,llP1,36,0,2,United Stat,4,1,1,...,2,0,0,7,0,0,246.621,3.820,23:47:23,20/04/2016
296,f271711d,11,llP1,36,0,2,United Stat,4,1,1,...,3,0,0,5,0,0,251.784,4.688,23:47:28,20/04/2016
297,f271711d,12,llP1,36,0,2,United Stat,4,1,1,...,0,0,0,7,0,0,260.930,8.703,23:47:37,20/04/2016
298,f271711d,13,llP1,36,0,2,United Stat,4,1,0,...,0,0,0,0,2,0,276.941,15.156,23:47:53,20/04/2016
299,XC900129,1,llP1,67,1,5,Algeria,4,0,1,...,4,0,2,6,0,0,53.856,0.000,11:28:40,20/04/2016
300,XC900129,2,llP1,67,1,5,Algeria,4,0,1,...,0,1,1,6,0,0,62.288,0.000,11:28:49,20/04/2016
301,XC900129,3,llP1,67,1,5,Algeria,4,0,1,...,5,0,2,8,0,0,75.558,0.000,11:29:02,20/04/2016
302,XC900129,4,llP1,67,1,5,Algeria,4,0,1,...,1,1,1,7,0,0,83.790,0.000,11:29:10,20/04/2016
303,XC900129,5,llP1,67,1,5,Algeria,4,0,1,...,2,1,0,5,0,0,90.733,0.000,11:29:17,20/04/2016
304,XC900129,6,llP1,67,1,5,Algeria,4,0,1,...,3,1,0,7,0,0,98.181,0.000,11:29:25,20/04/2016
305,XC900129,7,llP1,67,1,5,Algeria,4,0,1,...,1,0,0,7,0,0,103.125,2.557,11:29:29,20/04/2016
306,XC900129,8,llP1,67,1,5,Algeria,4,0,1,...,0,0,0,6,0,0,105.301,1.800,11:29:32,20/04/2016
307,XC900129,9,llP1,67,1,5,Algeria,4,0,1,...,2,0,0,5,0,0,107.317,1.758,11:29:34,20/04/2016
308,XC900129,10,llP1,67,1,5,Algeria,4,0,1,...,4,0,0,6,0,0,109.389,1.881,11:29:36,20/04/2016
309,XC900129,11,llP1,67,1,5,Algeria,4,0,1,...,3,0,0,7,0,0,110.949,1.363,11:29:37,20/04/2016
310,XC900129,12,llP1,67,1,5,Algeria,4,0,1,...,5,0,0,8,0,0,112.836,1.678,11:29:39,20/04/2016
311,XC900129,13,llP1,67,1,5,Algeria,4,0,0,...,0,0,0,0,1,0,117.012,3.980,11:29:43,20/04/2016

In [67]:
data.to_pickle('updated_trustworthy.p')

In [70]:
data2 = pd.read_pickle('updated_trustworthy.p')

In [72]:
data2.set_index(['subject','id'],inplace=True)

In [73]:
data2

            expCode  age  gender  ethnicity      country  education  \
subject  id
03c2782a 1     llP1   26       1          7  United Stat          4
         2     llP1   26       1          7  United Stat          4
         3     llP1   26       1          7  United Stat          4
         4     llP1   26       1          7  United Stat          4
         5     llP1   26       1          7  United Stat          4
         6     llP1   26       1          7  United Stat          4
         7     llP1   26       1          7  United Stat          4
         8     llP1   26       1          7  United Stat          4
         9     llP1   26       1          7  United Stat          4
         10    llP1   26       1          7  United Stat          4
         11    llP1   26       1          7  United Stat          4
         12    llP1   26       1          7  United Stat          4
         13    llP1   26       1          7  United Stat          4
1d72221b 1     llP1   44       1          2  United Stat          4
         2     llP1   44       1          2  United Stat          4
         3     llP1   44       1          2  United Stat          4
         4     llP1   44       1          2  United Stat          4
         5     llP1   44       1          2  United Stat          4
         6     llP1   44       1          2  United Stat          4
         7     llP1   44       1          2  United Stat          4
         8     llP1   44       1          2  United Stat          4
         9     llP1   44       1          2  United Stat          4
         10    llP1   44       1          2  United Stat          4
         11    llP1   44       1          2  United Stat          4
         12    llP1   44       1          2  United Stat          4
         13    llP1   44       1          2  United Stat          4
3d643351 1     llP1   21       0          2  United Stat          4
         2     llP1   21       0          2  United Stat          4
         3     llP1   21       0          2  United Stat          4
         4     llP1   21       0          2  United Stat          4
...             ...  ...     ...        ...          ...        ...
f2eb44cd 10    llP1   31       1          2  United Stat          5
         11    llP1   31       1          2  United Stat          5
         12    llP1   31       1          2  United Stat          5
         13    llP1   31       1          2  United Stat          5
f271711d 1     llP1   36       0          2  United Stat          4
         2     llP1   36       0          2  United Stat          4
         3     llP1   36       0          2  United Stat          4
         4     llP1   36       0          2  United Stat          4
         5     llP1   36       0          2  United Stat          4
         6     llP1   36       0          2  United Stat          4
         7     llP1   36       0          2  United Stat          4
         8     llP1   36       0          2  United Stat          4
         9     llP1   36       0          2  United Stat          4
         10    llP1   36       0          2  United Stat          4
         11    llP1   36       0          2  United Stat          4
         12    llP1   36       0          2  United Stat          4
         13    llP1   36       0          2  United Stat          4
XC900129 1     llP1   67       1          5      Algeria          4
         2     llP1   67       1          5      Algeria          4
         3     llP1   67       1          5      Algeria          4
         4     llP1   67       1          5      Algeria          4
         5     llP1   67       1          5      Algeria          4
         6     llP1   67       1          5      Algeria          4
         7     llP1   67       1          5      Algeria          4
         8     llP1   67       1          5      Algeria          4
         9     llP1   67       1          5      Algeria          4
         10    llP1   67       1          5      Algeria          4
         11    llP1   67       1          5      Algeria          4
         12    llP1   67       1          5      Algeria          4
         13    llP1   67       1          5      Algeria          4

             economics  quizAttempts  trialCount  condition  faceID  choice  \
subject  id
03c2782a 1           0             2           1          5       1       1
         2           0             2           2          4       2       1
         3           0             2           3          0       5       0
         4           0             2           4          3       4       1
         5           0             2           5          2       0       0
         6           0             2           6          1       3       1
         7           0             2           0          0       1       0
         8           0             2           0          0       0       0
         9           0             2           0          0       3       0
         10          0             2           0          0       4       0
         11          0             2           0          0       5       0
         12          0             2           0          0       2       0
         13          0             0           0          0       0       0
1d72221b 1           1             1           1          2       2       1
         2           1             1           2          4       3       0
         3           1             1           3          5       5       1
         4           1             1           4          0       4       0
         5           1             1           5          3       1       0
         6           1             1           6          1       0       0
         7           1             1           0          0       0       0
         8           1             1           0          0       5       0
         9           1             1           0          0       3       0
         10          1             1           0          0       2       0
         11          1             1           0          0       4       0
         12          1             1           0          0       1       0
         13          1             0           0          0       0       0
3d643351 1           0             5           1          4       2       1
         2           0             5           2          1       0       0
         3           0             5           3          2       5       1
         4           0             5           4          3       3       1
...                ...           ...         ...        ...     ...     ...
f2eb44cd 10          0             1           0          0       3       0
         11          0             1           0          0       0       0
         12          0             1           0          0       2       0
         13          0             0           0          0       0       0
f271711d 1           1             1           1          5       2       0
         2           1             1           2          3       4       1
         3           1             1           3          4       1       0
         4           1             1           4          2       5       1
         5           1             1           5          0       3       0
         6           1             1           6          1       0       0
         7           1             1           0          0       4       0
         8           1             1           0          0       5       0
         9           1             1           0          0       1       0
         10          1             1           0          0       2       0
         11          1             1           0          0       3       0
         12          1             1           0          0       0       0
         13          1             0           0          0       0       0
XC900129 1           0             1           1          4       4       0
         2           0             1           2          3       0       1
         3           0             1           3          5       5       0
         4           0             1           4          2       1       1
         5           0             1           5          0       2       1
         6           0             1           6          1       3       1
         7           0             1           0          0       1       0
         8           0             1           0          0       0       0
         9           0             1           0          0       2       0
         10          0             1           0          0       4       0
         11          0             1           0          0       3       0
         12          0             1           0          0       5       0
         13          0             0           0          0       0       0

             choiceCongruent  trustworthyRate  reasonForExp  reasonCorrect  \
subject  id
03c2782a 1                 2                8             0              0
         2                 2                7             0              0
         3                 1                6             0              0
         4                 1                6             0              0
         5                 0                8             0              0
         6                 0                6             0              0
         7                 0                8             0              0
         8                 0                8             0              0
         9                 0                6             0              0
         10                0                6             0              0
         11                0                6             0              0
         12                0                7             0              0
         13                0                0             2              0
1d72221b 1                 1                5             0              0
         2                 2                5             0              0
         3                 2                5             0              0
         4                 1                5             0              0
         5                 0                5             0              0
         6                 1                5             0              0
         7                 0                5             0              0
         8                 0                5             0              0
         9                 0                5             0              0
         10                0                5             0              0
         11                0                5             0              0
         12                0                5             0              0
         13                0                0             1              0
3d643351 1                 2                8             0              0
         2                 1                4             0              0
         3                 1                7             0              0
         4                 1                5             0              0
...                      ...              ...           ...            ...
f2eb44cd 10                0                6             0              0
         11                0                3             0              0
         12                0                3             0              0
         13                0                0             2              0
f271711d 1                 2                7             0              0
         2                 1                7             0              0
         3                 2                7             0              0
         4                 1                5             0              0
         5                 1                5             0              0
         6                 1                7             0              0
         7                 0                7             0              0
         8                 0                5             0              0
         9                 0                7             0              0
         10                0                7             0              0
         11                0                5             0              0
         12                0                7             0              0
         13                0                0             2              0
XC900129 1                 2                6             0              0
         2                 1                6             0              0
         3                 2                8             0              0
         4                 1                7             0              0
         5                 0                5             0              0
         6                 0                7             0              0
         7                 0                7             0              0
         8                 0                6             0              0
         9                 0                5             0              0
         10                0                6             0              0
         11                0                7             0              0
         12                0                8             0              0
         13                0                0             1              0

             elapsedTime  responseTime trialEndTime        date
subject  id
03c2782a 1       132.537         0.000     11:59:37  20/04/2016
         2       144.399         0.000     11:59:49  20/04/2016
         3       153.535         0.000     11:59:58  20/04/2016
         4       164.807         0.000     12:00:09  20/04/2016
         5       172.826         0.000     12:00:17  20/04/2016
         6       180.835         0.000     12:00:25  20/04/2016
         7       197.738        11.691     12:00:42  20/04/2016
         8       210.899        12.625     12:00:55  20/04/2016
         9       219.407         7.925     12:01:04  20/04/2016
         10      226.015         6.114     12:01:10  20/04/2016
         11      231.854         5.336     12:01:16  20/04/2016
         12      238.742         4.276     12:01:23  20/04/2016
         13      260.317        21.024     12:01:45  20/04/2016
1d72221b 1       186.610         0.000     12:07:23  20/04/2016
         2       194.804         0.000     12:07:31  20/04/2016
         3       203.449         0.000     12:07:39  20/04/2016
         4       211.292         0.000     12:07:47  20/04/2016
         5       222.884         0.000     12:07:59  20/04/2016
         6       233.716         0.000     12:08:10  20/04/2016
         7       249.513        10.928     12:08:26  20/04/2016
         8       253.939         3.967     12:08:30  20/04/2016
         9       260.137         5.724     12:08:36  20/04/2016
         10      264.913         4.287     12:08:41  20/04/2016
         11      269.903         4.475     12:08:46  20/04/2016
         12      273.855         3.495     12:08:50  20/04/2016
         13      290.801        16.461     12:09:07  20/04/2016
3d643351 1      1312.060         0.000     15:43:55  20/04/2016
         2      1321.460         0.000     15:44:04  20/04/2016
         3      1330.440         0.000     15:44:13  20/04/2016
         4      1338.950         0.000     15:44:22  20/04/2016
...                  ...           ...          ...         ...
f2eb44cd 10      235.435         5.366     18:39:57  20/04/2016
         11      239.329         3.421     18:40:01  20/04/2016
         12      243.076         3.281     18:40:05  20/04/2016
         13      260.105        16.569     18:40:22  20/04/2016
f271711d 1       159.176         0.000     23:45:55  20/04/2016
         2       168.270         0.000     23:46:04  20/04/2016
         3       176.415         0.000     23:46:12  20/04/2016
         4       193.572         0.000     23:46:30  20/04/2016
         5       203.695         0.000     23:46:40  20/04/2016
         6       216.080         0.000     23:46:52  20/04/2016
         7       231.538        11.016     23:47:08  20/04/2016
         8       238.268         5.880     23:47:14  20/04/2016
         9       242.358         3.615     23:47:18  20/04/2016
         10      246.621         3.820     23:47:23  20/04/2016
         11      251.784         4.688     23:47:28  20/04/2016
         12      260.930         8.703     23:47:37  20/04/2016
         13      276.941        15.156     23:47:53  20/04/2016
XC900129 1        53.856         0.000     11:28:40  20/04/2016
         2        62.288         0.000     11:28:49  20/04/2016
         3        75.558         0.000     11:29:02  20/04/2016
         4        83.790         0.000     11:29:10  20/04/2016
         5        90.733         0.000     11:29:17  20/04/2016
         6        98.181         0.000     11:29:25  20/04/2016
         7       103.125         2.557     11:29:29  20/04/2016
         8       105.301         1.800     11:29:32  20/04/2016
         9       107.317         1.758     11:29:34  20/04/2016
         10      109.389         1.881     11:29:36  20/04/2016
         11      110.949         1.363     11:29:37  20/04/2016
         12      112.836         1.678     11:29:39  20/04/2016
         13      117.012         3.980     11:29:43  20/04/2016

[312 rows x 20 columns]

In [79]:
data2.loc(['03c2782a'])

SyntaxError: invalid syntax (<ipython-input-79-e651011fdb85>, line 1)